export const countriesEn: Record<string, Object> = {
  AF: { name: 'Afghanistan', dial_code: '+93', currency: 'AFN' },
  AL: { name: 'Albania', dial_code: '+355', currency: 'ALL' },
  DZ: { name: 'Algeria', dial_code: '+213', currency: 'DZD' },
  AS: { name: 'American Samoa', dial_code: '+1 684', currency: 'EUR' },
  AD: { name: 'Andorra', dial_code: '+376', currency: 'EUR' },
  AO: { name: 'Angola', dial_code: '+244', currency: 'AOA' },
  AI: { name: 'Anguilla', dial_code: '+1 264', currency: 'XCD' },
  AG: {
    name: 'Antigua and Barbuda',
    dial_code: '+1268',
    currency: 'XCD',
  },
  AR: { name: 'Argentina', dial_code: '+54', currency: 'ARS' },
  AM: { name: 'Armenia', dial_code: '+374', currency: 'AMD' },
  AW: { name: 'Aruba', dial_code: '+297', currency: 'ANG' },
  AU: { name: 'Australia', dial_code: '+61', currency: 'AUD' },
  AT: { name: 'Austria', dial_code: '+43', currency: 'EUR' },
  AZ: { name: 'Azerbaijan', dial_code: '+994', currency: 'AZN' },
  BS: { name: 'Bahamas', dial_code: '+1 242', currency: 'BSD' },
  BH: { name: 'Bahrain', dial_code: '+973', currency: 'BHD' },
  BD: { name: 'Bangladesh', dial_code: '+880', currency: 'BDT' },
  BB: { name: 'Barbados', dial_code: '+1 246', currency: 'BBD' },
  BY: { name: 'Belarus', dial_code: '+375', currency: 'BYR' },
  BE: { name: 'Belgium', dial_code: '+32', currency: 'EUR' },
  BZ: { name: 'Belize', dial_code: '+501', currency: 'BZD' },
  BJ: { name: 'Benin', dial_code: '+229', currency: 'XOF' },
  BM: { name: 'Bermuda', dial_code: '+1 441', currency: 'BMD' },
  BT: { name: 'Bhutan', dial_code: '+975', currency: 'INR' },
  BO: {
    name: 'Bolivia, Plurinational State of',
    dial_code: '+591',
    currency: 'BOB',
  },
  BA: {
    name: 'Bosnia and Herzegovina',
    dial_code: '+387',
    currency: 'BAM',
  },
  BW: { name: 'Botswana', dial_code: '+267', currency: 'BWP' },
  BR: { name: 'Brazil', dial_code: '+55', currency: 'BRL' },
  IO: {
    name: 'British Indian Ocean Territory',
    dial_code: '+246',
    currency: 'USD',
  },
  BG: { name: 'Bulgaria', dial_code: '+359', currency: 'BGN' },
  BF: { name: 'Burkina Faso', dial_code: '+226', currency: 'XOF' },
  BI: { name: 'Burundi', dial_code: '+257', currency: 'BIF' },
  KH: { name: 'Cambodia', dial_code: '+855', currency: 'KHR' },
  CM: { name: 'Cameroon', dial_code: '+237', currency: 'XAF' },
  CA: { name: 'Canada', dial_code: '+1', currency: 'CAD' },
  CV: { name: 'Cape Verde', dial_code: '+238', currency: 'CVE' },
  KY: { name: 'Cayman Islands', dial_code: '+ 345', currency: 'KYD' },
  CF: {
    name: 'Central African Republic',
    dial_code: '+236',
    currency: 'XAF',
  },
  TD: { name: 'Chad', dial_code: '+235', currency: 'XAF' },
  CL: { name: 'Chile', dial_code: '+56', currency: 'CLP' },
  CN: { name: 'China', dial_code: '+86', currency: 'CNY' },
  CO: { name: 'Colombia', dial_code: '+57', currency: 'COP' },
  KM: { name: 'Comoros', dial_code: '+269', currency: 'KMF' },
  CG: { name: 'Congo', dial_code: '+242', currency: 'XAF' },
  CD: {
    name: 'Democratic Republic of the Congo',
    dial_code: '+243',
    currency: 'CDF',
  },
  CK: { name: 'Cook Islands', dial_code: '+682', currency: 'NZD' },
  CR: { name: 'Costa Rica', dial_code: '+506', currency: 'CRC' },
  CI: { name: "Côte d'Ivoire", dial_code: '+225', currency: 'XOF' },
  HR: { name: 'Croatia', dial_code: '+385', currency: 'HRK' },
  CU: { name: 'Cuba', dial_code: '+53', currency: 'CUP' },
  CW: { name: 'Curaçao', dial_code: '+599', currency: 'ANG' },
  CY: { name: 'Cyprus', dial_code: '+537', currency: 'CYP' },
  CZ: { name: 'Czech Republic', dial_code: '+420', currency: 'CZK' },
  DK: { name: 'Denmark', dial_code: '+45', currency: 'DKK' },
  DJ: { name: 'Djibouti', dial_code: '+253', currency: 'DJF' },
  DM: { name: 'Dominica', dial_code: '+1 767', currency: 'XCD' },
  DO: {
    name: 'Dominican Republic',
    dial_code: '+1 849',
    currency: 'DOP',
  },
  EC: { name: 'Ecuador', dial_code: '+593', currency: 'ECS' },
  EG: { name: 'Egypt', dial_code: '+20', currency: 'EGP' },
  SV: { name: 'El Salvador', dial_code: '+503', currency: 'SVC' },
  GQ: { name: 'Equatorial Guinea', dial_code: '+240', currency: 'XAF' },
  ER: { name: 'Eritrea', dial_code: '+291', currency: 'ETB' },
  EE: { name: 'Estonia', dial_code: '+372', currency: 'EEK' },
  ET: { name: 'Ethiopia', dial_code: '+251', currency: 'ETB' },
  FK: {
    name: 'Falkland Islands (Malvinas)',
    dial_code: '+500',
    currency: 'FKP',
  },
  FO: { name: 'Faroe Islands', dial_code: '+298', currency: 'DKK' },
  FJ: { name: 'Fiji', dial_code: '+679', currency: 'FJD' },
  FI: { name: 'Finland', dial_code: '+358', currency: 'EUR' },
  FR: { name: 'France', dial_code: '+33', currency: 'EUR' },
  PF: { name: 'French Polynesia', dial_code: '+689', currency: 'XPF' },
  GA: { name: 'Gabon', dial_code: '+241', currency: 'XAF' },
  GM: { name: 'Gambia', dial_code: '+220', currency: 'GMD' },
  GE: { name: 'Georgia', dial_code: '+995', currency: 'GEL' },
  DE: { name: 'Germany', dial_code: '+49', currency: 'EUR' },
  GH: { name: 'Ghana', dial_code: '+233', currency: 'GHS' },
  GI: { name: 'Gibraltar', dial_code: '+350', currency: 'GIP' },
  GR: { name: 'Greece', dial_code: '+30', currency: 'EUR' },
  GL: { name: 'Greenland', dial_code: '+299', currency: 'DKK' },
  GD: { name: 'Grenada', dial_code: '+1 473', currency: 'XCD' },
  GU: { name: 'Guam', dial_code: '+1 671', currency: 'USD' },
  GT: { name: 'Guatemala', dial_code: '+502', currency: 'GTQ' },
  GG: { name: 'Guernsey', dial_code: '+44', currency: 'GGP' },
  GN: { name: 'Guinea', dial_code: '+224', currency: 'GNF' },
  GW: { name: 'Guinea-Bissau', dial_code: '+245', currency: 'XOF' },
  HT: { name: 'Haiti', dial_code: '+509', currency: 'HTG' },
  HN: { name: 'Honduras', dial_code: '+504', currency: 'HNL' },
  HK: { name: 'Hong Kong', dial_code: '+852', currency: 'HKD' },
  HU: { name: 'Hungary', dial_code: '+36', currency: 'HUF' },
  IS: { name: 'Iceland', dial_code: '+354', currency: 'ISK' },
  IN: { name: 'India', dial_code: '+91', currency: 'INR' },
  ID: { name: 'Indonesia', dial_code: '+62', currency: 'IDR' },
  IR: {
    name: 'Iran, Islamic Republic of',
    dial_code: '+98',
    currency: 'IRR',
  },
  IQ: { name: 'Iraq', dial_code: '+964', currency: 'IQD' },
  IE: { name: 'Ireland', dial_code: '+353', currency: 'EUR' },
  IM: { name: 'Isle of Man', dial_code: '+44', currency: 'GBP' },
  IL: { name: 'Israel', dial_code: '+972', currency: 'ILS' },
  IT: { name: 'Italy', dial_code: '+39', currency: 'EUR' },
  JM: { name: 'Jamaica', dial_code: '+1 876', currency: 'JMD' },
  JP: { name: 'Japan', dial_code: '+81', currency: 'JPY' },
  JE: { name: 'Jersey', dial_code: '+44', currency: 'GBP' },
  JO: { name: 'Jordan', dial_code: '+962', currency: 'JOD' },
  KZ: { name: 'Kazakhstan', dial_code: '+7 7', currency: 'KZT' },
  KE: { name: 'Kenya', dial_code: '+254', currency: 'KES' },
  KI: { name: 'Kiribati', dial_code: '+686', currency: 'AUD' },
  KP: { name: 'North Korea', dial_code: '+850', currency: 'KPW' },
  KR: { name: 'South Korea', dial_code: '+82', currency: 'KRW' },
  KW: { name: 'Kuwait', dial_code: '+965', currency: 'KWD' },
  KG: { name: 'Kyrgyzstan', dial_code: '+996', currency: 'KGS' },
  LA: {
    name: "Lao People's Democratic Republic",
    dial_code: '+856',
    currency: 'LAK',
  },
  LV: { name: 'Latvia', dial_code: '+371', currency: 'LVL' },
  LB: { name: 'Lebanon', dial_code: '+961', currency: 'LBP' },
  LS: { name: 'Lesotho', dial_code: '+266', currency: 'LSL' },
  LR: { name: 'Liberia', dial_code: '+231', currency: 'LRD' },
  LY: { name: 'Libya', dial_code: '+218', currency: 'LYD' },
  LI: { name: 'Liechtenstein', dial_code: '+423', currency: 'CHF' },
  LT: { name: 'Lithuania', dial_code: '+370', currency: 'LTL' },
  LU: { name: 'Luxembourg', dial_code: '+352', currency: 'EUR' },
  MO: { name: 'Macao', dial_code: '+853', currency: 'MOP' },
  MK: {
    name: 'Republic of Macedonia',
    dial_code: '+389',
    currency: 'MKD',
  },
  MG: { name: 'Madagascar', dial_code: '+261', currency: 'MGA' },
  MW: { name: 'Malawi', dial_code: '+265', currency: 'MWK' },
  MY: { name: 'Malaysia', dial_code: '+60', currency: 'MYR' },
  MV: { name: 'Maldives', dial_code: '+960', currency: 'MVR' },
  ML: { name: 'Mali', dial_code: '+223', currency: 'XOF' },
  MT: { name: 'Malta', dial_code: '+356', currency: 'MTL' },
  MH: { name: 'Marshall Islands', dial_code: '+692', currency: 'USD' },
  MQ: { name: 'Martinique', dial_code: '+596', currency: 'EUR' },
  MR: { name: 'Mauritania', dial_code: '+222', currency: 'MRO' },
  MU: { name: 'Mauritius', dial_code: '+230', currency: 'MUR' },
  MX: { name: 'Mexico', dial_code: '+52', currency: 'MXN' },
  FM: {
    name: 'Micronesia, Federated States of',
    dial_code: '+691',
    currency: 'USD',
  },
  MD: {
    name: 'Republic of Moldova',
    dial_code: '+373',
    currency: 'MDL',
  },
  MC: { name: 'Monaco', dial_code: '+377', currency: 'EUR' },
  MN: { name: 'Mongolia', dial_code: '+976', currency: 'MNT' },
  ME: { name: 'Montenegro', dial_code: '+382', currency: 'EUR' },
  MS: { name: 'Montserrat', dial_code: '+1664', currency: 'XCD' },
  MA: { name: 'Morocco', dial_code: '+212', currency: 'MAD' },
  MZ: { name: 'Mozambique', dial_code: '+258', currency: 'MZN' },
  MM: { name: 'Myanmar', dial_code: '+95', currency: 'MMK' },
  NA: { name: 'Namibia', dial_code: '+264', currency: 'NAD' },
  NR: { name: 'Nauru', dial_code: '+674', currency: 'AUD' },
  NP: { name: 'Nepal', dial_code: '+977', currency: 'NPR' },
  NL: { name: 'Netherlands', dial_code: '+31', currency: 'EUR' },
  NZ: { name: 'New Zealand', dial_code: '+64', currency: 'NZD' },
  NI: { name: 'Nicaragua', dial_code: '+505', currency: 'NIO' },
  NE: { name: 'Niger', dial_code: '+227', currency: 'XOF' },
  NG: { name: 'Nigeria', dial_code: '+234', currency: 'NGN' },
  NU: { name: 'Niue', dial_code: '+683', currency: 'NZD' },
  NF: { name: 'Norfolk Island', dial_code: '+672', currency: 'AUD' },
  MP: {
    name: 'Northern Mariana Islands',
    dial_code: '+1 670',
    currency: 'USD',
  },
  NO: { name: 'Norway', dial_code: '+47', currency: 'NOK' },
  OM: { name: 'Oman', dial_code: '+968', currency: 'OMR' },
  PK: { name: 'Pakistan', dial_code: '+92', currency: 'PKR' },
  PW: { name: 'Palau', dial_code: '+680', currency: 'USD' },
  PS: {
    name: 'Palestinian Territory',
    dial_code: '+970',
    currency: 'JOD',
  },
  PA: { name: 'Panama', dial_code: '+507', currency: 'PAB' },
  PG: { name: 'Papua New Guinea', dial_code: '+675', currency: 'PGK' },
  PY: { name: 'Paraguay', dial_code: '+595', currency: 'PYG' },
  PE: { name: 'Peru', dial_code: '+51', currency: 'PEN' },
  PH: { name: 'Philippines', dial_code: '+63', currency: 'PHP' },
  PN: { name: 'Pitcairn', dial_code: '+872', currency: 'NZD' },
  PL: { name: 'Poland', dial_code: '+48', currency: 'PLN' },
  PT: { name: 'Portugal', dial_code: '+351', currency: 'EUR' },
  PR: { name: 'Puerto Rico', dial_code: '+1 939', currency: 'USD' },
  QA: { name: 'Qatar', dial_code: '+974', currency: 'QAR' },
  RO: { name: 'Romania', dial_code: '+40', currency: 'RON' },
  RU: { name: 'Russian', dial_code: '+7', currency: 'RUB' },
  RW: { name: 'Rwanda', dial_code: '+250', currency: 'RWF' },
  KN: {
    name: 'Saint Kitts and Nevis',
    dial_code: '+1 869',
    currency: 'XCD',
  },
  WS: { name: 'Samoa', dial_code: '+685', currency: 'EUR' },
  SM: { name: 'San Marino', dial_code: '+378', currency: 'EUR' },
  ST: {
    name: 'Sao Tome and Principe',
    dial_code: '+239',
    currency: 'STD',
  },
  SA: { name: 'Saudi Arabia', dial_code: '+966', currency: 'SAR' },
  SN: { name: 'Senegal', dial_code: '+221', currency: 'XOF' },
  RS: { name: 'Serbia', dial_code: '+381', currency: 'RSD' },
  SC: { name: 'Seychelles', dial_code: '+248', currency: 'SCR' },
  SL: { name: 'Sierra Leone', dial_code: '+232', currency: 'SLL' },
  SG: { name: 'Singapore', dial_code: '+65', currency: 'SGD' },
  SX: { name: 'Sint Maarten', dial_code: '+599', currency: 'ANG' },
  SK: { name: 'Slovakia', dial_code: '+421', currency: 'SKK' },
  SI: { name: 'Slovenia', dial_code: '+386', currency: 'EUR' },
  SB: { name: 'Solomon Islands', dial_code: '+677', currency: 'SBD' },
  SO: { name: 'Somalia', dial_code: '+252', currency: 'SOS' },
  ZA: { name: 'South Africa', dial_code: '+27', currency: 'ZAR' },
  SS: { name: 'South Sudan', dial_code: '+211', currency: 'SSP' },
  ES: { name: 'Spain', dial_code: '+34', currency: 'EUR' },
  LK: { name: 'Sri Lanka', dial_code: '+94', currency: 'LKR' },
  SD: { name: 'Sudan', dial_code: '+249', currency: 'SDG' },
  SR: { name: 'Suriname', dial_code: '+597', currency: 'SRD' },
  SZ: { name: 'Swaziland', dial_code: '+268', currency: 'SZL' },
  SE: { name: 'Sweden', dial_code: '+46', currency: 'SEK' },
  CH: { name: 'Switzerland', dial_code: '+41', currency: 'CHF' },
  SY: { name: 'Syria', dial_code: '+963', currency: 'SYP' },
  TW: {
    name: 'Taiwan, Province of China',
    dial_code: '+886',
    currency: 'TWD',
  },
  TJ: { name: 'Tajikistan', dial_code: '+992', currency: 'TJS' },
  TZ: { name: 'Tanzania', dial_code: '+255', currency: 'TZS' },
  TH: { name: 'Thailand', dial_code: '+66', currency: 'THB' },
  TG: { name: 'Togo', dial_code: '+228', currency: 'XOF' },
  TK: { name: 'Tokelau', dial_code: '+690', currency: 'NZD' },
  TO: { name: 'Tonga', dial_code: '+676', currency: 'TOP' },
  TT: {
    name: 'Trinidad and Tobago',
    dial_code: '+1 868',
    currency: 'TTD',
  },
  TN: { name: 'Tunisia', dial_code: '+216', currency: 'TND' },
  TR: { name: 'Turkey', dial_code: '+90', currency: 'TRY' },
  TM: { name: 'Turkmenistan', dial_code: '+993', currency: 'TMT' },
  TC: {
    name: 'Turks and Caicos Islands',
    dial_code: '+1 649',
    currency: 'USD',
  },
  TV: { name: 'Tuvalu', dial_code: '+688', currency: 'AUD' },
  UG: { name: 'Uganda', dial_code: '+256', currency: 'UGX' },
  UA: { name: 'Ukraine', dial_code: '+380', currency: 'UAH' },
  AE: {
    name: 'United Arab Emirates',
    dial_code: '+971',
    currency: 'AED',
  },
  GB: { name: 'United Kingdom', dial_code: '+44', currency: 'GBP' },
  US: { name: 'United States', dial_code: '+1', currency: 'USD' },
  UY: { name: 'Uruguay', dial_code: '+598', currency: 'UYU' },
  UZ: { name: 'Uzbekistan', dial_code: '+998', currency: 'UZS' },
  VU: { name: 'Vanuatu', dial_code: '+678', currency: 'VUV' },
  VE: {
    name: 'Venezuela, Bolivarian Republic of',
    dial_code: '+58',
    currency: 'VEF',
  },
  VN: { name: 'Viet Nam', dial_code: '+84', currency: 'VND' },
  VI: { name: 'Virgin Islands', dial_code: '+1 340', currency: 'USD' },
  YE: { name: 'Yemen', dial_code: '+967', currency: 'YER' },
  ZM: { name: 'Zambia', dial_code: '+260', currency: 'ZMK' },
  ZW: { name: 'Zimbabwe', dial_code: '+263', currency: 'ZWD' },
};

export const countriesTr = {
  AF: { name: 'Afghanistan', dial_code: '+93', currency: 'AFN' },
  AL: { name: 'Albania', dial_code: '+355', currency: 'ALL' },
  DZ: { name: 'Algeria', dial_code: '+213', currency: 'DZD' },
  AS: { name: 'American Samoa', dial_code: '+1 684', currency: 'EUR' },
  AD: { name: 'Andorra', dial_code: '+376', currency: 'EUR' },
  AO: { name: 'Angola', dial_code: '+244', currency: 'AOA' },
  AI: { name: 'Anguilla', dial_code: '+1 264', currency: 'XCD' },
  AG: {
    name: 'Antigua and Barbuda',
    dial_code: '+1268',
    currency: 'XCD',
  },
  AR: { name: 'Argentina', dial_code: '+54', currency: 'ARS' },
  AM: { name: 'Armenia', dial_code: '+374', currency: 'AMD' },
  AW: { name: 'Aruba', dial_code: '+297', currency: 'ANG' },
  AU: { name: 'Australia', dial_code: '+61', currency: 'AUD' },
  AT: { name: 'Austria', dial_code: '+43', currency: 'EUR' },
  AZ: { name: 'Azerbaijan', dial_code: '+994', currency: 'AZN' },
  BS: { name: 'Bahamas', dial_code: '+1 242', currency: 'BSD' },
  BH: { name: 'Bahrain', dial_code: '+973', currency: 'BHD' },
  BD: { name: 'Bangladesh', dial_code: '+880', currency: 'BDT' },
  BB: { name: 'Barbados', dial_code: '+1 246', currency: 'BBD' },
  BY: { name: 'Belarus', dial_code: '+375', currency: 'BYR' },
  BE: { name: 'Belgium', dial_code: '+32', currency: 'EUR' },
  BZ: { name: 'Belize', dial_code: '+501', currency: 'BZD' },
  BJ: { name: 'Benin', dial_code: '+229', currency: 'XOF' },
  BM: { name: 'Bermuda', dial_code: '+1 441', currency: 'BMD' },
  BT: { name: 'Bhutan', dial_code: '+975', currency: 'INR' },
  BO: {
    name: 'Bolivia, Plurinational State of',
    dial_code: '+591',
    currency: 'BOB',
  },
  BA: {
    name: 'Bosnia and Herzegovina',
    dial_code: '+387',
    currency: 'BAM',
  },
  BW: { name: 'Botswana', dial_code: '+267', currency: 'BWP' },
  BR: { name: 'Brazil', dial_code: '+55', currency: 'BRL' },
  IO: {
    name: 'British Indian Ocean Territory',
    dial_code: '+246',
    currency: 'USD',
  },
  BG: { name: 'Bulgaria', dial_code: '+359', currency: 'BGN' },
  BF: { name: 'Burkina Faso', dial_code: '+226', currency: 'XOF' },
  BI: { name: 'Burundi', dial_code: '+257', currency: 'BIF' },
  KH: { name: 'Cambodia', dial_code: '+855', currency: 'KHR' },
  CM: { name: 'Cameroon', dial_code: '+237', currency: 'XAF' },
  CA: { name: 'Canada', dial_code: '+1', currency: 'CAD' },
  CV: { name: 'Cape Verde', dial_code: '+238', currency: 'CVE' },
  KY: { name: 'Cayman Islands', dial_code: '+ 345', currency: 'KYD' },
  CF: {
    name: 'Central African Republic',
    dial_code: '+236',
    currency: 'XAF',
  },
  TD: { name: 'Chad', dial_code: '+235', currency: 'XAF' },
  CL: { name: 'Chile', dial_code: '+56', currency: 'CLP' },
  CN: { name: 'China', dial_code: '+86', currency: 'CNY' },
  CO: { name: 'Colombia', dial_code: '+57', currency: 'COP' },
  KM: { name: 'Comoros', dial_code: '+269', currency: 'KMF' },
  CG: { name: 'Congo', dial_code: '+242', currency: 'XAF' },
  CD: {
    name: 'Democratic Republic of the Congo',
    dial_code: '+243',
    currency: 'CDF',
  },
  CK: { name: 'Cook Islands', dial_code: '+682', currency: 'NZD' },
  CR: { name: 'Costa Rica', dial_code: '+506', currency: 'CRC' },
  CI: { name: "Côte d'Ivoire", dial_code: '+225', currency: 'XOF' },
  HR: { name: 'Croatia', dial_code: '+385', currency: 'HRK' },
  CU: { name: 'Cuba', dial_code: '+53', currency: 'CUP' },
  CW: { name: 'Curaçao', dial_code: '+599', currency: 'ANG' },
  CY: { name: 'Cyprus', dial_code: '+537', currency: 'CYP' },
  CZ: { name: 'Czech Republic', dial_code: '+420', currency: 'CZK' },
  DK: { name: 'Denmark', dial_code: '+45', currency: 'DKK' },
  DJ: { name: 'Djibouti', dial_code: '+253', currency: 'DJF' },
  DM: { name: 'Dominica', dial_code: '+1 767', currency: 'XCD' },
  DO: {
    name: 'Dominican Republic',
    dial_code: '+1 849',
    currency: 'DOP',
  },
  EC: { name: 'Ecuador', dial_code: '+593', currency: 'ECS' },
  EG: { name: 'Egypt', dial_code: '+20', currency: 'EGP' },
  SV: { name: 'El Salvador', dial_code: '+503', currency: 'SVC' },
  GQ: { name: 'Equatorial Guinea', dial_code: '+240', currency: 'XAF' },
  ER: { name: 'Eritrea', dial_code: '+291', currency: 'ETB' },
  EE: { name: 'Estonia', dial_code: '+372', currency: 'EEK' },
  ET: { name: 'Ethiopia', dial_code: '+251', currency: 'ETB' },
  FK: {
    name: 'Falkland Islands (Malvinas)',
    dial_code: '+500',
    currency: 'FKP',
  },
  FO: { name: 'Faroe Islands', dial_code: '+298', currency: 'DKK' },
  FJ: { name: 'Fiji', dial_code: '+679', currency: 'FJD' },
  FI: { name: 'Finland', dial_code: '+358', currency: 'EUR' },
  FR: { name: 'France', dial_code: '+33', currency: 'EUR' },
  PF: { name: 'French Polynesia', dial_code: '+689', currency: 'XPF' },
  GA: { name: 'Gabon', dial_code: '+241', currency: 'XAF' },
  GM: { name: 'Gambia', dial_code: '+220', currency: 'GMD' },
  GE: { name: 'Georgia', dial_code: '+995', currency: 'GEL' },
  DE: { name: 'Germany', dial_code: '+49', currency: 'EUR' },
  GH: { name: 'Ghana', dial_code: '+233', currency: 'GHS' },
  GI: { name: 'Gibraltar', dial_code: '+350', currency: 'GIP' },
  GR: { name: 'Greece', dial_code: '+30', currency: 'EUR' },
  GL: { name: 'Greenland', dial_code: '+299', currency: 'DKK' },
  GD: { name: 'Grenada', dial_code: '+1 473', currency: 'XCD' },
  GU: { name: 'Guam', dial_code: '+1 671', currency: 'USD' },
  GT: { name: 'Guatemala', dial_code: '+502', currency: 'GTQ' },
  GG: { name: 'Guernsey', dial_code: '+44', currency: 'GGP' },
  GN: { name: 'Guinea', dial_code: '+224', currency: 'GNF' },
  GW: { name: 'Guinea-Bissau', dial_code: '+245', currency: 'XOF' },
  HT: { name: 'Haiti', dial_code: '+509', currency: 'HTG' },
  HN: { name: 'Honduras', dial_code: '+504', currency: 'HNL' },
  HK: { name: 'Hong Kong', dial_code: '+852', currency: 'HKD' },
  HU: { name: 'Hungary', dial_code: '+36', currency: 'HUF' },
  IS: { name: 'Iceland', dial_code: '+354', currency: 'ISK' },
  IN: { name: 'India', dial_code: '+91', currency: 'INR' },
  ID: { name: 'Indonesia', dial_code: '+62', currency: 'IDR' },
  IR: {
    name: 'Iran, Islamic Republic of',
    dial_code: '+98',
    currency: 'IRR',
  },
  IQ: { name: 'Iraq', dial_code: '+964', currency: 'IQD' },
  IE: { name: 'Ireland', dial_code: '+353', currency: 'EUR' },
  IM: { name: 'Isle of Man', dial_code: '+44', currency: 'GBP' },
  IL: { name: 'Israel', dial_code: '+972', currency: 'ILS' },
  IT: { name: 'Italy', dial_code: '+39', currency: 'EUR' },
  JM: { name: 'Jamaica', dial_code: '+1 876', currency: 'JMD' },
  JP: { name: 'Japan', dial_code: '+81', currency: 'JPY' },
  JE: { name: 'Jersey', dial_code: '+44', currency: 'GBP' },
  JO: { name: 'Jordan', dial_code: '+962', currency: 'JOD' },
  KZ: { name: 'Kazakhstan', dial_code: '+7 7', currency: 'KZT' },
  KE: { name: 'Kenya', dial_code: '+254', currency: 'KES' },
  KI: { name: 'Kiribati', dial_code: '+686', currency: 'AUD' },
  KP: { name: 'North Korea', dial_code: '+850', currency: 'KPW' },
  KR: { name: 'South Korea', dial_code: '+82', currency: 'KRW' },
  KW: { name: 'Kuwait', dial_code: '+965', currency: 'KWD' },
  KG: { name: 'Kyrgyzstan', dial_code: '+996', currency: 'KGS' },
  LA: {
    name: "Lao People's Democratic Republic",
    dial_code: '+856',
    currency: 'LAK',
  },
  LV: { name: 'Latvia', dial_code: '+371', currency: 'LVL' },
  LB: { name: 'Lebanon', dial_code: '+961', currency: 'LBP' },
  LS: { name: 'Lesotho', dial_code: '+266', currency: 'LSL' },
  LR: { name: 'Liberia', dial_code: '+231', currency: 'LRD' },
  LY: { name: 'Libya', dial_code: '+218', currency: 'LYD' },
  LI: { name: 'Liechtenstein', dial_code: '+423', currency: 'CHF' },
  LT: { name: 'Lithuania', dial_code: '+370', currency: 'LTL' },
  LU: { name: 'Luxembourg', dial_code: '+352', currency: 'EUR' },
  MO: { name: 'Macao', dial_code: '+853', currency: 'MOP' },
  MK: {
    name: 'Republic of Macedonia',
    dial_code: '+389',
    currency: 'MKD',
  },
  MG: { name: 'Madagascar', dial_code: '+261', currency: 'MGA' },
  MW: { name: 'Malawi', dial_code: '+265', currency: 'MWK' },
  MY: { name: 'Malaysia', dial_code: '+60', currency: 'MYR' },
  MV: { name: 'Maldives', dial_code: '+960', currency: 'MVR' },
  ML: { name: 'Mali', dial_code: '+223', currency: 'XOF' },
  MT: { name: 'Malta', dial_code: '+356', currency: 'MTL' },
  MH: { name: 'Marshall Islands', dial_code: '+692', currency: 'USD' },
  MQ: { name: 'Martinique', dial_code: '+596', currency: 'EUR' },
  MR: { name: 'Mauritania', dial_code: '+222', currency: 'MRO' },
  MU: { name: 'Mauritius', dial_code: '+230', currency: 'MUR' },
  MX: { name: 'Mexico', dial_code: '+52', currency: 'MXN' },
  FM: {
    name: 'Micronesia, Federated States of',
    dial_code: '+691',
    currency: 'USD',
  },
  MD: {
    name: 'Republic of Moldova',
    dial_code: '+373',
    currency: 'MDL',
  },
  MC: { name: 'Monaco', dial_code: '+377', currency: 'EUR' },
  MN: { name: 'Mongolia', dial_code: '+976', currency: 'MNT' },
  ME: { name: 'Montenegro', dial_code: '+382', currency: 'EUR' },
  MS: { name: 'Montserrat', dial_code: '+1664', currency: 'XCD' },
  MA: { name: 'Morocco', dial_code: '+212', currency: 'MAD' },
  MZ: { name: 'Mozambique', dial_code: '+258', currency: 'MZN' },
  MM: { name: 'Myanmar', dial_code: '+95', currency: 'MMK' },
  NA: { name: 'Namibia', dial_code: '+264', currency: 'NAD' },
  NR: { name: 'Nauru', dial_code: '+674', currency: 'AUD' },
  NP: { name: 'Nepal', dial_code: '+977', currency: 'NPR' },
  NL: { name: 'Netherlands', dial_code: '+31', currency: 'EUR' },
  NZ: { name: 'New Zealand', dial_code: '+64', currency: 'NZD' },
  NI: { name: 'Nicaragua', dial_code: '+505', currency: 'NIO' },
  NE: { name: 'Niger', dial_code: '+227', currency: 'XOF' },
  NG: { name: 'Nigeria', dial_code: '+234', currency: 'NGN' },
  NU: { name: 'Niue', dial_code: '+683', currency: 'NZD' },
  NF: { name: 'Norfolk Island', dial_code: '+672', currency: 'AUD' },
  MP: {
    name: 'Northern Mariana Islands',
    dial_code: '+1 670',
    currency: 'USD',
  },
  NO: { name: 'Norway', dial_code: '+47', currency: 'NOK' },
  OM: { name: 'Oman', dial_code: '+968', currency: 'OMR' },
  PK: { name: 'Pakistan', dial_code: '+92', currency: 'PKR' },
  PW: { name: 'Palau', dial_code: '+680', currency: 'USD' },
  PS: {
    name: 'Palestinian Territory',
    dial_code: '+970',
    currency: 'JOD',
  },
  PA: { name: 'Panama', dial_code: '+507', currency: 'PAB' },
  PG: { name: 'Papua New Guinea', dial_code: '+675', currency: 'PGK' },
  PY: { name: 'Paraguay', dial_code: '+595', currency: 'PYG' },
  PE: { name: 'Peru', dial_code: '+51', currency: 'PEN' },
  PH: { name: 'Philippines', dial_code: '+63', currency: 'PHP' },
  PN: { name: 'Pitcairn', dial_code: '+872', currency: 'NZD' },
  PL: { name: 'Poland', dial_code: '+48', currency: 'PLN' },
  PT: { name: 'Portugal', dial_code: '+351', currency: 'EUR' },
  PR: { name: 'Puerto Rico', dial_code: '+1 939', currency: 'USD' },
  QA: { name: 'Qatar', dial_code: '+974', currency: 'QAR' },
  RO: { name: 'Romania', dial_code: '+40', currency: 'RON' },
  RU: { name: 'Russian', dial_code: '+7', currency: 'RUB' },
  RW: { name: 'Rwanda', dial_code: '+250', currency: 'RWF' },
  KN: {
    name: 'Saint Kitts and Nevis',
    dial_code: '+1 869',
    currency: 'XCD',
  },
  WS: { name: 'Samoa', dial_code: '+685', currency: 'EUR' },
  SM: { name: 'San Marino', dial_code: '+378', currency: 'EUR' },
  ST: {
    name: 'Sao Tome and Principe',
    dial_code: '+239',
    currency: 'STD',
  },
  SA: { name: 'Saudi Arabia', dial_code: '+966', currency: 'SAR' },
  SN: { name: 'Senegal', dial_code: '+221', currency: 'XOF' },
  RS: { name: 'Serbia', dial_code: '+381', currency: 'RSD' },
  SC: { name: 'Seychelles', dial_code: '+248', currency: 'SCR' },
  SL: { name: 'Sierra Leone', dial_code: '+232', currency: 'SLL' },
  SG: { name: 'Singapore', dial_code: '+65', currency: 'SGD' },
  SX: { name: 'Sint Maarten', dial_code: '+599', currency: 'ANG' },
  SK: { name: 'Slovakia', dial_code: '+421', currency: 'SKK' },
  SI: { name: 'Slovenia', dial_code: '+386', currency: 'EUR' },
  SB: { name: 'Solomon Islands', dial_code: '+677', currency: 'SBD' },
  SO: { name: 'Somalia', dial_code: '+252', currency: 'SOS' },
  ZA: { name: 'South Africa', dial_code: '+27', currency: 'ZAR' },
  SS: { name: 'South Sudan', dial_code: '+211', currency: 'SSP' },
  ES: { name: 'Spain', dial_code: '+34', currency: 'EUR' },
  LK: { name: 'Sri Lanka', dial_code: '+94', currency: 'LKR' },
  SD: { name: 'Sudan', dial_code: '+249', currency: 'SDG' },
  SR: { name: 'Suriname', dial_code: '+597', currency: 'SRD' },
  SZ: { name: 'Swaziland', dial_code: '+268', currency: 'SZL' },
  SE: { name: 'Sweden', dial_code: '+46', currency: 'SEK' },
  CH: { name: 'Switzerland', dial_code: '+41', currency: 'CHF' },
  SY: { name: 'Syria', dial_code: '+963', currency: 'SYP' },
  TW: {
    name: 'Taiwan, Province of China',
    dial_code: '+886',
    currency: 'TWD',
  },
  TJ: { name: 'Tajikistan', dial_code: '+992', currency: 'TJS' },
  TZ: { name: 'Tanzania', dial_code: '+255', currency: 'TZS' },
  TH: { name: 'Thailand', dial_code: '+66', currency: 'THB' },
  TG: { name: 'Togo', dial_code: '+228', currency: 'XOF' },
  TK: { name: 'Tokelau', dial_code: '+690', currency: 'NZD' },
  TO: { name: 'Tonga', dial_code: '+676', currency: 'TOP' },
  TT: {
    name: 'Trinidad and Tobago',
    dial_code: '+1 868',
    currency: 'TTD',
  },
  TN: { name: 'Tunisia', dial_code: '+216', currency: 'TND' },
  TR: { name: 'Turkey', dial_code: '+90', currency: 'TRY' },
  TM: { name: 'Turkmenistan', dial_code: '+993', currency: 'TMT' },
  TC: {
    name: 'Turks and Caicos Islands',
    dial_code: '+1 649',
    currency: 'USD',
  },
  TV: { name: 'Tuvalu', dial_code: '+688', currency: 'AUD' },
  UG: { name: 'Uganda', dial_code: '+256', currency: 'UGX' },
  UA: { name: 'Ukraine', dial_code: '+380', currency: 'UAH' },
  AE: {
    name: 'United Arab Emirates',
    dial_code: '+971',
    currency: 'AED',
  },
  GB: { name: 'United Kingdom', dial_code: '+44', currency: 'GBP' },
  US: { name: 'United States', dial_code: '+1', currency: 'USD' },
  UY: { name: 'Uruguay', dial_code: '+598', currency: 'UYU' },
  UZ: { name: 'Uzbekistan', dial_code: '+998', currency: 'UZS' },
  VU: { name: 'Vanuatu', dial_code: '+678', currency: 'VUV' },
  VE: {
    name: 'Venezuela, Bolivarian Republic of',
    dial_code: '+58',
    currency: 'VEF',
  },
  VN: { name: 'Viet Nam', dial_code: '+84', currency: 'VND' },
  VI: { name: 'Virgin Islands', dial_code: '+1 340', currency: 'USD' },
  YE: { name: 'Yemen', dial_code: '+967', currency: 'YER' },
  ZM: { name: 'Zambia', dial_code: '+260', currency: 'ZMK' },
  ZW: { name: 'Zimbabwe', dial_code: '+263', currency: 'ZWD' },
};
