export enum routes {
  home = '/',
  register = '/register',
  login = '/login',
  dashboard = '/dashboard',
  changePassword = '/change-password',
  identifyVerification = '/kyc',
  twoFactorAuth = '/two-factor-auth',
  market = '/market',
  accountManagement = '/account',
  history = '/history',
  wallet = '/wallet',
  exchange = '/exchange',
  spotWallet = '/spot-wallet',
  buy = '/buy',
  trade = '/trade',
  staking = '/staking',
  rewardCenter = '/reward-center',
  referral = '/referral',
  earnings = '/earnings',
  deposit = '/deposit',
  subAccount = '/sub-account',
}
